# Generated by Django 4.1.7 on 2023-04-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracking', '0002_rename_contributor_contributor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='issuetracking.project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('FA', 'Faible'), ('MO', 'Moyenne'), ('EL', 'Elevée')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('FA', 'A faire'), ('EC', 'En cours'), ('TE', 'Terminé')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BU', 'Bug'), ('AM', 'Amélioration'), ('TA', 'Tâche')], max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('IO', 'IOs'), ('AD', 'Android')], max_length=2),
        ),
    ]
